name: flet_circular_slider
description: Flet extension wrapping sleek_circular_slider Flutter package
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: ">=0.80.5 <2.0.0"
  flutter:
    sdk: flutter
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
